# Generated by Django 3.1.5 on 2021-01-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.IntegerField()),
                ('ended', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
