# Generated by Django 3.1.5 on 2021-01-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='created',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='ended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='uid',
            field=models.IntegerField(default=1),
        ),
    ]
