# Generated by Django 3.1.5 on 2021-01-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20210127_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
