# Generated by Django 3.1.5 on 2021-01-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
